### ISSUE TITLE
No keyboard input in text field

### ISSUE THREAD

**Issue by Armitage1982** [crystalboxes/dear-imgui-unity#1]
Hi,

It seems that it is impossible to write with the keyboard in the text fields.

However, the example panel does receive keyboard input. But even in this panel, no text can be entered.

Also, I noticed a difference in ASCII code perhaps related to my problem :
In Dear ImGui, the "a" key return 46
In Unity, Keycode.A return 97 _(as expected)_

As a consequence, the following example:
`ImGui.Text($"Texture sample {ImGui.IsKeyDown((int)KeyCode.A)}");`
doesn't work :-(

Other than that, awesome integration!

**Comment by crystalboxes** [comment]
Fixed (a6ba4c425558e0a2047940b2eb286192540c2e80)

**Comment by Armitage1982** [comment]
Hi,

Nice fix 👍 
Something is wrong with **ImGuiUnityIL.dll**. When I reload the Unity project and run it for a second time the editor crash. So I moved the IOController back into the renderer class and addapt a few things. If you want to check : https://pastebin.com/XwJNLLqb

Happy Holiday 😃

**Comment by crystalboxes** [comment]
Hey,
Thanks for the info, I fixed it. The IOController had to be initialized before the renderer since it contained ImGui context creation.
b2e7c24d3cef9c8dd9951720c0bd7236baa43538
